env: "dev"
http_server: 
    address: "localhost:8082"
db:
  host: "dpg-d39u1jd6ubrc73eeeui0-a"
  port: 5432
  user: "websocket_chat_server_user"
  password: "CcPMMvxO13yQQktbwHevPptCJvuTQbXp"
  name: "websocket_chat_server"
  sslmode: "require"
jwt:
  secret: "change-me"
  issuer: "students-api"
  access_ttl_minutes: 60
